# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 20:57
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160118_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=django_markdown.models.MarkdownField(),
        ),
    ]
